name: Flutter CI (develop)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  flutter_ci:
    name: Build and Test Flutter App on develop
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter (versi stable)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependensi
      - name: Install dependencies
        run: flutter pub get

      # 4. Analisa kode (cek eror/warning)
      - name: Flutter analyze
        run: flutter analyze

      # 5. Jalankan test (bisa placeholder test masih oke)
      - name: Flutter test
        run: flutter test

      # 6. Build APK debug (bukti build berhasil)
      - name: Build APK (debug)
        run: flutter build apk --debug
